# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name=b'Code')),
                ('longname', models.CharField(max_length=100, verbose_name=b'Name')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name=b'Latitude')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name=b'Latitude')),
            ],
        ),
    ]
